# version: "3.8"

services:
  # docker run -d --name search2ai -v "$(pwd)":/app -w /app -p 3014:3014 node:18-alpine sh -c "npm install && npm start"
  # docker run -d --name search2ai --network compse -v "$(pwd)":/app -w /app -e PORT=7860 node:18-alpine sh -c "npm install && npm start"
  search2ai:
    image: node:18-alpine
    container_name: search2ai
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3014:3014"

  # docker run --rm -d -p 8080:8080 -v "${PWD}/searxng:/etc/searxng" -v “${PWD}/searxng：/etc/searxng” -e "BASE_URL=http://0.0.0.0:8080/" -e "INSTANCE_NAME=searxng" searxng/searxng
  # . 修改 settings.yml
  # 当您安装 SearXNG 时，默认的输出格式是 HTML 格式。您需要激活 JSON 格式。请将以下行添加到 settings.yml 文件中。如前面的示例所示，settings.yml 文件位于 ${PWD}/searxng/settings.yml
  #   # formats: [html, csv, json, rss]
  #   formats:
  #     - html
  #     - json    # <-- 添加这一行
  # searxng:
  #   container_name: searxng
  #   image: searxng/searxng
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     - BASE_URL=http://0.0.0.0:8090/
  #     - INSTANCE_NAME=searxng
  #   volumes:
  #     - ./data/searxng:/etc/searxng
  #   restart: unless-stopped
